services:
  backend:
    image: portfolio-backend
    build: ./server
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_PATH=/data/portfolio.db
    volumes:
      - data_volume:/data
    restart: always

  frontend:
    image: portfolio-frontend
    user: "0:0"
    entrypoint: ["nginx", "-g", "daemon off;"]
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always

volumes:
  data_volume:
